id = "naproche"
name = "Naproche"
version = "0.0.1"
schema_version = 1
authors = ["Jules"]
description = "Naproche support for Zed"
repository = "https://github.com/naproche/naproche"

[grammars.naproche]
repository = "https://github.com/latex-lsp/tree-sitter-latex"
commit = "2945d898517e57d606f85c3b997c6530691507d3"

[languages.naproche]
name = "Naproche"
grammar = "naproche"
path_suffixes = ["ftl.tex"]

[lsp]
server_name = "naproche-ls"
command = "python"
args = ["-m", "naproche.lsp.server"]
